/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkoutsRouteImport } from './routes/workouts'
import { Route as ExercisesRouteImport } from './routes/exercises'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutsIndexRouteImport } from './routes/workouts.index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises.index'
import { Route as WorkoutsNewRouteImport } from './routes/workouts.new'
import { Route as WorkoutsCompletedRouteImport } from './routes/workouts.completed'
import { Route as ExercisesNewRouteImport } from './routes/exercises.new'
import { Route as ExercisesIdRouteImport } from './routes/exercises.$id'
import { Route as ExercisesIdIndexRouteImport } from './routes/exercises.$id.index'
import { Route as WorkoutsIdSessionRouteImport } from './routes/workouts.$id.session'
import { Route as WorkoutsIdEditRouteImport } from './routes/workouts.$id.edit'
import { Route as ExercisesIdEditRouteImport } from './routes/exercises.$id.edit'

const WorkoutsRoute = WorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesRoute = ExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutsIndexRoute = WorkoutsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkoutsRoute,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExercisesRoute,
} as any)
const WorkoutsNewRoute = WorkoutsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => WorkoutsRoute,
} as any)
const WorkoutsCompletedRoute = WorkoutsCompletedRouteImport.update({
  id: '/completed',
  path: '/completed',
  getParentRoute: () => WorkoutsRoute,
} as any)
const ExercisesNewRoute = ExercisesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ExercisesRoute,
} as any)
const ExercisesIdRoute = ExercisesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ExercisesRoute,
} as any)
const ExercisesIdIndexRoute = ExercisesIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ExercisesIdRoute,
} as any)
const WorkoutsIdSessionRoute = WorkoutsIdSessionRouteImport.update({
  id: '/$id/session',
  path: '/$id/session',
  getParentRoute: () => WorkoutsRoute,
} as any)
const WorkoutsIdEditRoute = WorkoutsIdEditRouteImport.update({
  id: '/$id/edit',
  path: '/$id/edit',
  getParentRoute: () => WorkoutsRoute,
} as any)
const ExercisesIdEditRoute = ExercisesIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => ExercisesIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/workouts': typeof WorkoutsRouteWithChildren
  '/exercises/$id': typeof ExercisesIdRouteWithChildren
  '/exercises/new': typeof ExercisesNewRoute
  '/workouts/completed': typeof WorkoutsCompletedRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/exercises/$id/edit': typeof ExercisesIdEditRoute
  '/workouts/$id/edit': typeof WorkoutsIdEditRoute
  '/workouts/$id/session': typeof WorkoutsIdSessionRoute
  '/exercises/$id/': typeof ExercisesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/exercises/new': typeof ExercisesNewRoute
  '/workouts/completed': typeof WorkoutsCompletedRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/exercises': typeof ExercisesIndexRoute
  '/workouts': typeof WorkoutsIndexRoute
  '/exercises/$id/edit': typeof ExercisesIdEditRoute
  '/workouts/$id/edit': typeof WorkoutsIdEditRoute
  '/workouts/$id/session': typeof WorkoutsIdSessionRoute
  '/exercises/$id': typeof ExercisesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/exercises': typeof ExercisesRouteWithChildren
  '/workouts': typeof WorkoutsRouteWithChildren
  '/exercises/$id': typeof ExercisesIdRouteWithChildren
  '/exercises/new': typeof ExercisesNewRoute
  '/workouts/completed': typeof WorkoutsCompletedRoute
  '/workouts/new': typeof WorkoutsNewRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/workouts/': typeof WorkoutsIndexRoute
  '/exercises/$id/edit': typeof ExercisesIdEditRoute
  '/workouts/$id/edit': typeof WorkoutsIdEditRoute
  '/workouts/$id/session': typeof WorkoutsIdSessionRoute
  '/exercises/$id/': typeof ExercisesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/exercises'
    | '/workouts'
    | '/exercises/$id'
    | '/exercises/new'
    | '/workouts/completed'
    | '/workouts/new'
    | '/exercises/'
    | '/workouts/'
    | '/exercises/$id/edit'
    | '/workouts/$id/edit'
    | '/workouts/$id/session'
    | '/exercises/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/exercises/new'
    | '/workouts/completed'
    | '/workouts/new'
    | '/exercises'
    | '/workouts'
    | '/exercises/$id/edit'
    | '/workouts/$id/edit'
    | '/workouts/$id/session'
    | '/exercises/$id'
  id:
    | '__root__'
    | '/'
    | '/exercises'
    | '/workouts'
    | '/exercises/$id'
    | '/exercises/new'
    | '/workouts/completed'
    | '/workouts/new'
    | '/exercises/'
    | '/workouts/'
    | '/exercises/$id/edit'
    | '/workouts/$id/edit'
    | '/workouts/$id/session'
    | '/exercises/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExercisesRoute: typeof ExercisesRouteWithChildren
  WorkoutsRoute: typeof WorkoutsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workouts': {
      id: '/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof WorkoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises': {
      id: '/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof ExercisesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workouts/': {
      id: '/workouts/'
      path: '/'
      fullPath: '/workouts/'
      preLoaderRoute: typeof WorkoutsIndexRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof ExercisesRoute
    }
    '/workouts/new': {
      id: '/workouts/new'
      path: '/new'
      fullPath: '/workouts/new'
      preLoaderRoute: typeof WorkoutsNewRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/workouts/completed': {
      id: '/workouts/completed'
      path: '/completed'
      fullPath: '/workouts/completed'
      preLoaderRoute: typeof WorkoutsCompletedRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/exercises/new': {
      id: '/exercises/new'
      path: '/new'
      fullPath: '/exercises/new'
      preLoaderRoute: typeof ExercisesNewRouteImport
      parentRoute: typeof ExercisesRoute
    }
    '/exercises/$id': {
      id: '/exercises/$id'
      path: '/$id'
      fullPath: '/exercises/$id'
      preLoaderRoute: typeof ExercisesIdRouteImport
      parentRoute: typeof ExercisesRoute
    }
    '/exercises/$id/': {
      id: '/exercises/$id/'
      path: '/'
      fullPath: '/exercises/$id/'
      preLoaderRoute: typeof ExercisesIdIndexRouteImport
      parentRoute: typeof ExercisesIdRoute
    }
    '/workouts/$id/session': {
      id: '/workouts/$id/session'
      path: '/$id/session'
      fullPath: '/workouts/$id/session'
      preLoaderRoute: typeof WorkoutsIdSessionRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/workouts/$id/edit': {
      id: '/workouts/$id/edit'
      path: '/$id/edit'
      fullPath: '/workouts/$id/edit'
      preLoaderRoute: typeof WorkoutsIdEditRouteImport
      parentRoute: typeof WorkoutsRoute
    }
    '/exercises/$id/edit': {
      id: '/exercises/$id/edit'
      path: '/edit'
      fullPath: '/exercises/$id/edit'
      preLoaderRoute: typeof ExercisesIdEditRouteImport
      parentRoute: typeof ExercisesIdRoute
    }
  }
}

interface ExercisesIdRouteChildren {
  ExercisesIdEditRoute: typeof ExercisesIdEditRoute
  ExercisesIdIndexRoute: typeof ExercisesIdIndexRoute
}

const ExercisesIdRouteChildren: ExercisesIdRouteChildren = {
  ExercisesIdEditRoute: ExercisesIdEditRoute,
  ExercisesIdIndexRoute: ExercisesIdIndexRoute,
}

const ExercisesIdRouteWithChildren = ExercisesIdRoute._addFileChildren(
  ExercisesIdRouteChildren,
)

interface ExercisesRouteChildren {
  ExercisesIdRoute: typeof ExercisesIdRouteWithChildren
  ExercisesNewRoute: typeof ExercisesNewRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
}

const ExercisesRouteChildren: ExercisesRouteChildren = {
  ExercisesIdRoute: ExercisesIdRouteWithChildren,
  ExercisesNewRoute: ExercisesNewRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
}

const ExercisesRouteWithChildren = ExercisesRoute._addFileChildren(
  ExercisesRouteChildren,
)

interface WorkoutsRouteChildren {
  WorkoutsCompletedRoute: typeof WorkoutsCompletedRoute
  WorkoutsNewRoute: typeof WorkoutsNewRoute
  WorkoutsIndexRoute: typeof WorkoutsIndexRoute
  WorkoutsIdEditRoute: typeof WorkoutsIdEditRoute
  WorkoutsIdSessionRoute: typeof WorkoutsIdSessionRoute
}

const WorkoutsRouteChildren: WorkoutsRouteChildren = {
  WorkoutsCompletedRoute: WorkoutsCompletedRoute,
  WorkoutsNewRoute: WorkoutsNewRoute,
  WorkoutsIndexRoute: WorkoutsIndexRoute,
  WorkoutsIdEditRoute: WorkoutsIdEditRoute,
  WorkoutsIdSessionRoute: WorkoutsIdSessionRoute,
}

const WorkoutsRouteWithChildren = WorkoutsRoute._addFileChildren(
  WorkoutsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExercisesRoute: ExercisesRouteWithChildren,
  WorkoutsRoute: WorkoutsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
